<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_apiuserspage2</name>
   <tag></tag>
   <elementGuidId>d1e6b559-c272-4455-ae5c-9e1c5e4233c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f845bc9-25c1-4521-a0b6-7c36d8c64135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>dde5e019-56c7-4b46-a331-d9a59106a75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>755f6b98-bab1-4396-bf4c-ab6830a1e3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/api/users?page=2</value>
      <webElementGuid>f76e2a8d-c881-4043-b95a-77eccb28a2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;console&quot;)/div[@class=&quot;output&quot;]/div[@class=&quot;request&quot;]/p[@class=&quot;request-title&quot;]/strong[1]/a[@class=&quot;link try-link&quot;]/span[@class=&quot;url&quot;]</value>
      <webElementGuid>9ccd563e-33ba-4662-b158-2eba63825368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='console']/div[2]/div/p/strong/a/span</value>
      <webElementGuid>79628554-6c72-475a-8945-f12def67e4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delayed response'])[1]/following::span[1]</value>
      <webElementGuid>aaf023e8-3b76-420c-8c34-60a315a8aa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://reqres.in/#support-heading'])[1]/preceding::span[2]</value>
      <webElementGuid>a07f9f64-6a64-42e8-8e23-1a279e0e977b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/api/users?page=2']/parent::*</value>
      <webElementGuid>f081fda4-fea5-4422-81ec-8a6a8d03940c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>fd58ce5a-85c8-4687-8e2f-144b91583087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '/api/users?page=2' or . = '/api/users?page=2')]</value>
      <webElementGuid>d9adb519-14cd-4846-9934-9e0ac1fb02be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
